[project]
name = "markdown-converter"
version = "0.0.1"
description = "Hello World."
requires-python = ">=3.12"
readme = "README.md"
authors = [
    { name = "Vardhan Shorewala" }
]

dependencies = [
    "requests>=2.31.0,<3.0",
    "chromadb>=0.3.23,<1.0",
    "openai>=1.50,<2.0",
    "transformers>=4.31,<5.0",
    "PyPDF2>=3.0.1,<3.1",
    "torch>=2.5,<3.0",
    "flask>=3.0,<3.5",
    "psycopg2>=2.6,<3.0",
    "pandas>=2.1.0,<2.3.0",
    "arxivscraper>=0.0.5,<1.0",
    "web3>=7.4,<8.0"
]