# Database Creator Configuration

# Neo4j connection parameters
neo4j:
  uri: ${NEO4J_URI}
  username: ${NEO4J_USERNAME}
  password: ${NEO4J_PASSWORD}

# User configuration
user:
  email: "vardhanshorewala@berkeley.edu"

# Database components
components:
  converter:
    - openai
  chunker:
    - paragraph
  embedder:
    - openai

# Vector database configuration
vector_db:
  path: descidb/database
# CIDs file paths to check (will be combined with user-specific paths)
cids_file_paths:
  - cids.txt
  - temp/cids.txt
