# Database Creator Configuration

# Neo4j connection parameters
neo4j:
  uri: ${NEO4J_URI}
  username: ${NEO4J_USERNAME}
  password: ${NEO4J_PASSWORD}

# User configuration
user:
  email: "vardhanshorewala@berkeley.edu"

# Vector database configuration
vector_db:
  path: descidb/database