# Evaluation Configuration

# User configuration
user_email: "vardhanshorewala@gmail.com"

# Model parameters
model_name: "openai/gpt-3.5-turbo-0613"

# Query parameters
query: "What are the citations for the paper 'Improving K-means clustering with enhanced firefly algorithms'?"

# Database path (null for default)
db_path: null

# Output directory (null for default)
output_dir: null
