# Evaluation Configuration

# Model parameters
model_name: "openai/gpt-3.5-turbo-0613"

# Query parameters
query: "What is MINT-DFC"

# Collection parameters
collections:
  - openai_paragraph_openai
  - openai_fixed_length_openai

# Database path (null for default)
db_path: null

# Output directory (null for default)
output_dir: null
